baseURL = 'https://yassinsassi.com/'
languageCode = 'en-us'
title = 'Yassins Blog'
theme = "nightfall"

[params]
footerHtml = '© 2025 Yassin Sassi'
user = "yassin"
hostname = "yassinsassi.com"
    [params.author]
    name = "Yassin Sassi"

[menu]
   [[menu.header]]
    name = "about me"
    weight = 0
    url = "/about"
  [[menu.header]]
    name = "posts"
    weight = 10
    url = "/posts"

    